from flask import Flask, send_file
import tensorflow as tf
from PIL import Image
import io
from api import generator
import numpy as np

#Initialize Flask app
app = Flask(__name__)

CODING_SIZE = 10

def generate_image():
    """
    Returns an image generated by passing a random vector 
    through the Generator of a trained GAN.
    """
    z = tf.random.normal([1,CODING_SIZE])
    output = generator(z).numpy()
    scaled_output = (output[0]+1)*255/2
    image = Image.fromarray(scaled_output.astype(np.uint8))
    return image

def serve_image(image):
    """
    Send image to client as JPEG

    Arguments:
        image (PIL.Image) - Image object to be sent
    """
    img_io = io.BytesIO()
    image.save(img_io, 'JPEG', quality=100)
    img_io.seek(0)
    return send_file(img_io, mimetype='image/jpeg')

@app.route('/')
def main():
    """
    Main API route.
    """
    image = generate_image()
    return serve_image(image)

